import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#fbfaf8',
  '--slot4-page-text': '#151528',
  '--slot4-panel-bg': '#f3f0ec',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#6d6a7f',
  '--slot4-soft-muted-text': '#9a96aa',
  '--slot4-accent': '#7a0bc0',
  '--slot4-accent-fill': '#7a0bc0',
  '--slot4-accent-soft': '#f7d5ee',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#101223',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#e7e3eb',
  '--slot4-cream': '#fbfaf8',
  '--slot4-warm': '#f3f0ec',
  '--slot4-lavender': '#f5e9ff',
  '--slot4-gray': '#ece8f2',
  '--slot4-indigo': '#270082',
  '--slot4-indigo-2': '#1a1a40',
  '--slot4-pink': '#fa58b6',
  '--slot4-gold': '#f6d58f',
  '--slot4-soft-bg': '#f6f2ee',
  '--slot4-soft-accent': 'rgba(122,11,192,0.1)',
  '--slot4-body-gradient': 'radial-gradient(circle at top center, rgba(250,88,182,0.07), transparent 32%), linear-gradient(180deg, #fdfcf9 0%, #fbfaf8 100%)',
  '--editable-page-bg': '#fbfaf8',
  '--editable-page-text': '#151528',
  '--editable-container': '1240px',
  '--editable-border': '#e7e0ea',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#151528',
  '--editable-nav-active': '#7a0bc0',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#101223',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#ffffff',
  '--editable-footer-text': '#151528',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_18px_40px_rgba(16,20,44,0.08)]',
  shadowStrong: 'shadow-[0_28px_70px_rgba(7,10,30,0.22)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(10,12,28,0.04),rgba(10,12,28,0.76))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[140px] shrink-0 snap-start sm:w-[160px]',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.32em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[1.02] tracking-[-0.05em] sm:text-5xl lg:text-[4rem]',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.04em] sm:text-4xl',
    body: 'text-base leading-relaxed',
  },
  surface: {
    card: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.75rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.75rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold tracking-[0.01em] text-[var(--slot4-page-text)] transition duration-200 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)] active:scale-[0.98]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full ${editablePalette.accentBg} px-6 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-200 hover:brightness-95 active:scale-[0.98]`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.5rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:shadow-[0_22px_48px_rgba(16,20,44,0.14)]',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Change the full site color palette in editableRootStyle first; all homepage sections consume those CSS variables.',
  'Keep page structure in src/editable/sections/HomeSections.tsx so AI can redesign the whole home experience in one file.',
  'Use wide readable grids; never create skinny columns for paragraphs or cards.',
  'Use horizontal rails for dense post browsing, like the MysteryCoder reference layout.',
  'Keep dynamic post fetching intact; do not replace posts with mock arrays.',
  'Use postHref() for all post links so task-specific routes keep working.',
] as const
